#! /usr/bin/env bash

clear;
echo -e "\nAtualizando Repositórios.\n";
sudo apt update -y;
echo -e "\nRepositórios Atualizados.\n"
sleep 2s;
clear;
echo -e "\nAtualizando Programas e Removendo Lixo.\n"
sudo apt upgrade -y;sudo apt autoremove -y;
echo -e "\nProgramas Atualizados e Lixos Removidos.\n"
sleep 2s;
clear;
echo -e "\n\tSistema Atualizado com Sucesso!\n\tFique a vontade $USER!\n"
