#! /usr/bin/env bash

clear;

echo "##################################################"
echo "#####   INICIANDO O TESTE DE VELOCIDADE DE   #####"
echo "##### CONEXÃO À REDE MUNDIAL DE COMPUTADORES #####"
echo "##################################################"

while [[ true ]] ;
do
	echo ""
	date;
	speedtest-cli | grep --color "Download";

done
