#! /usr/bin/env bash

clear;

echo "##################################################"
echo "#####      INICIANDO O TESTE DE PING AO      #####"
echo "#####          SITE: www.google.com          #####"
echo "##################################################"

while [[ true ]] ;
do
    ping www.google.com | grep --color "time="
done
